
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'left+-left*/rightUMINUSINTD NAME NUMBERstatement : NAME "=" expressionstatement : expressionexpression : expression \'+\' expression\n                  | expression \'-\' expression\n                  | expression \'*\' expression\n                  | expression \'%\' expression\n                  | expression INTD expression\n                  | expression \',\' expression\n                  | expression \'/\' expressionLIST : \'(\' expression \',\' expression \')\' \n            | \'(\' expression \',\' expression \',\' \')\' LIST : \'(\' expression \',\' \')\'LIST : \'(\' \',\' \')\'\n            | \'(\' \')\' expression : LISTexpression : \'-\' expression %prec UMINUSexpression : \'(\' expression \')\'expression : NUMBERexpression : NAME'
    
_lr_action_items = {'NAME':([0,4,6,8,9,10,11,12,13,14,15,30,34,],[2,17,17,17,17,17,17,17,17,17,17,17,17,]),'-':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,],[4,-19,10,4,-15,4,-18,4,4,4,4,4,4,4,4,-16,-19,10,-14,10,-3,-4,-5,10,10,10,-9,-17,4,-13,10,-12,4,-10,-11,]),'(':([0,4,6,8,9,10,11,12,13,14,15,30,34,],[6,6,6,6,6,6,6,6,6,6,6,6,6,]),'NUMBER':([0,4,6,8,9,10,11,12,13,14,15,30,34,],[7,7,7,7,7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,5,7,16,17,19,21,22,23,24,25,26,27,28,29,31,33,35,36,],[0,-19,-2,-15,-18,-16,-19,-14,-1,-3,-4,-5,-6,-7,-8,-9,-17,-13,-12,-10,-11,]),'=':([2,],[8,]),'+':([2,3,5,7,16,17,18,19,21,22,23,24,25,26,27,28,29,31,32,33,35,36,],[-19,9,-15,-18,-16,-19,9,-14,9,-3,-4,-5,9,9,9,-9,-17,-13,9,-12,-10,-11,]),'*':([2,3,5,7,16,17,18,19,21,22,23,24,25,26,27,28,29,31,32,33,35,36,],[-19,11,-15,-18,-16,-19,11,-14,11,11,11,-5,11,11,11,-9,-17,-13,11,-12,-10,-11,]),'%':([2,3,5,7,16,17,18,19,21,22,23,24,25,26,27,28,29,31,32,33,35,36,],[-19,12,-15,-18,-16,-19,12,-14,12,-3,-4,-5,12,12,12,-9,-17,-13,12,-12,-10,-11,]),'INTD':([2,3,5,7,16,17,18,19,21,22,23,24,25,26,27,28,29,31,32,33,35,36,],[-19,13,-15,-18,-16,-19,13,-14,13,-3,-4,-5,13,13,13,-9,-17,-13,13,-12,-10,-11,]),',':([2,3,5,6,7,16,17,18,19,21,22,23,24,25,26,27,28,29,31,32,33,35,36,],[-19,14,-15,20,-18,-16,-19,30,-14,14,-3,-4,-5,14,14,14,-9,-17,-13,34,-12,-10,-11,]),'/':([2,3,5,7,16,17,18,19,21,22,23,24,25,26,27,28,29,31,32,33,35,36,],[-19,15,-15,-18,-16,-19,15,-14,15,15,15,-5,15,15,15,-9,-17,-13,15,-12,-10,-11,]),')':([5,6,7,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,],[-15,19,-18,-16,-19,29,-14,31,-3,-4,-5,-6,-7,-8,-9,-17,33,-13,35,-12,36,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,6,8,9,10,11,12,13,14,15,30,34,],[3,16,18,21,22,23,24,25,26,27,28,32,27,]),'LIST':([0,4,6,8,9,10,11,12,13,14,15,30,34,],[5,5,5,5,5,5,5,5,5,5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME = expression','statement',3,'p_statement_assign','calcx.py',53),
  ('statement -> expression','statement',1,'p_statement_expr','calcx.py',58),
  ('expression -> expression + expression','expression',3,'p_expression_binop','calcx.py',63),
  ('expression -> expression - expression','expression',3,'p_expression_binop','calcx.py',64),
  ('expression -> expression * expression','expression',3,'p_expression_binop','calcx.py',65),
  ('expression -> expression % expression','expression',3,'p_expression_binop','calcx.py',66),
  ('expression -> expression INTD expression','expression',3,'p_expression_binop','calcx.py',67),
  ('expression -> expression , expression','expression',3,'p_expression_binop','calcx.py',68),
  ('expression -> expression / expression','expression',3,'p_expression_binop','calcx.py',69),
  ('LIST -> ( expression , expression )','LIST',5,'p_list','calcx.py',97),
  ('LIST -> ( expression , expression , )','LIST',6,'p_list','calcx.py',98),
  ('LIST -> ( expression , )','LIST',4,'p_singleton','calcx.py',102),
  ('LIST -> ( , )','LIST',3,'p_elist','calcx.py',106),
  ('LIST -> ( )','LIST',2,'p_elist','calcx.py',107),
  ('expression -> LIST','expression',1,'p_expression_list','calcx.py',111),
  ('expression -> - expression','expression',2,'p_expression_uminus','calcx.py',115),
  ('expression -> ( expression )','expression',3,'p_expression_group','calcx.py',120),
  ('expression -> NUMBER','expression',1,'p_expression_number','calcx.py',125),
  ('expression -> NAME','expression',1,'p_expression_name','calcx.py',130),
]
